name: Build

on:
  push:
    branches: [ dev, stable ]
  pull_request:
    branches: [ dev, stable ]
  schedule:
    - cron: '0 0 */16 * *'
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build-native:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-2019, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: |
          cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE -B build -S .
          cmake --build build --config $BUILD_TYPE

  build-emscripten:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - uses: mymindstorm/setup-emsdk@v12

     - name: Build
       shell: bash
       run: |
         emcmake cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE -B build -S .
         cmake --build build --config $BUILD_TYPE

